# Generated by Django 5.2.8 on 2025-11-17 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=50)),
                ('channel', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('order', models.IntegerField()),
                ('is_final', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=50)),
                ('channel', models.CharField(max_length=50)),
                ('client_type', models.CharField(default='adult', max_length=50)),
                ('sport', models.CharField(blank=True, max_length=50)),
                ('trainer', models.CharField(blank=True, max_length=50)),
                ('pre_trial_status', models.CharField(default='none', max_length=50)),
                ('trial_status', models.CharField(default='none', max_length=50)),
                ('result', models.CharField(default='none', max_length=50)),
                ('amount', models.FloatField(default=0)),
                ('currency', models.CharField(default='KGS', max_length=10)),
                ('comment', models.TextField(blank=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='leads.request')),
                ('stage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='leads.stage')),
            ],
        ),
    ]
